FileVersion = 1
Projects = {Sample01_BasicApplication = {Path = "Samples/Sample01_BasicApplication"}, "Sedulous.Core" = {Path = "Sedulous/Sedulous.Core"}, "Sedulous.Framework" = {Path = "Sedulous/Sedulous.Framework"}}
WorkspaceFolders = {Dependencies = ["corlib"], Sedulous = ["Sedulous.Core", "Sedulous.Framework"], Samples = ["Sample01_BasicApplication"]}

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
