FileVersion = 1
Projects = {Sample01_BasicApplication = {Path = "Samples/Sample01_BasicApplication"}, "Sedulous.Core" = {Path = "Sedulous/Sedulous.Core"}, "Sedulous.Framework" = {Path = "Sedulous/Sedulous.Framework"}, "Sedulous.SDL" = {Path = "Sedulous/Sedulous.SDL"}, SDL2 = "*", BeefBugs01 = {Path = "Debug/BeefBugs01"}, BeefBugs02 = {Path = "Debug/BeefBugs02"}, TimerTest = {Path = "Debug/TimerTest"}, "Sedulous.RHI" = {Path = "Sedulous/Sedulous.RHI"}, Bulkan = {Path = "Dependencies/Bulkan"}}
WorkspaceFolders = {Dependencies = ["corlib", "SDL2", "Bulkan"], Sedulous = ["Sedulous.Core", "Sedulous.Framework", "Sedulous.SDL", "Sedulous.RHI"], Samples = ["Sample01_BasicApplication"], Debug = ["BeefBugs01", "BeefBugs02", "TimerTest"]}

[Workspace]
StartupProject = "Sample01_BasicApplication"
