FileVersion = 1
Projects = {Sample01_BasicApplication = {Path = "Samples/Sample01_BasicApplication"}, "Sedulous.Core" = {Path = "Sedulous/Sedulous.Core"}, "Sedulous.Framework" = {Path = "Sedulous/Sedulous.Framework"}, "Sedulous.SDL" = {Path = "Sedulous/Sedulous.SDL"}, SDL2 = "*", BeefBugs = {Path = "Beef/BeefBugs"}}
WorkspaceFolders = {Dependencies = ["corlib", "SDL2"], Sedulous = ["Sedulous.Core", "Sedulous.Framework", "Sedulous.SDL"], Samples = ["Sample01_BasicApplication"], Beef = ["BeefBugs"]}

[Workspace]
StartupProject = "Sample01_BasicApplication"
